Separate "Lint and Build" Workflow (#93)
Additionally:
- Auto-commit pre-release `package.json` updates in "Publish Pre-Release" workflow
- Comment-out time-consuming install/build/lint steps for faster iterations
- Add `contents:write` permission for `publish-prerelease` GHA
- Add `npm run docs` to GitHub Actions CI/CD
- Try `Co-authored-by: <actor>` for GitHub Actions commit, https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line

diff --git a/.github/workflows/publish-prerelease.yml b/.github/workflows/publish-prerelease.yml
--- a/.github/workflows/publish-prerelease.yml
+++ b/.github/workflows/publish-prerelease.yml
@@ -1,27 +1,20 @@
 name: Publish Node.js Pre-Release
 
 on:
-  push:
+  workflow_run:
+    workflows:
+      - Lint and Build
+    types:
+      - completed
     branches: [issue-93-gh-actions]
 
 jobs:
-  build:
+  publish-prerelease:
     runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 16
-      - run: npm ci
-      - run: npm run lint
-      - run: npm run browserify
-
-  publish-gpr:
-    needs: build
-    runs-on: ubuntu-latest
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     permissions:
       packages: write
-      contents: read
+      contents: write
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
@@ -29,7 +22,32 @@ jobs:
           node-version: 16
           registry-url: https://npm.pkg.github.com/
       - run: npm ci
-#      - run: npm run prepare
-      - run: npm publish --tag=NEXT
+      - run: npm run prepare
+      - run: npm run docs
+      - name: Publish Pre-Release
+        run: |
+          PKG_VERSION=$(npm version prerelease)
+          npm publish --tag=next
+          PUBLISH_AS_IS=$?
+          if [[ $PUBLISH_AS_IS -eq 0 ]]; then
+            echo "Pre-release $PKG_VERSION published."
+            git config --local user.email "actions@github.com"
+            git config --local user.name "GitHub Actions"
+            git add README.md package.json package-lock.json
+            git status
+            git commit -m"[skip ci] Pre-release :package: \`$PKG_VERSION\` by :robot:
+
+          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
+          "
+            git log -n 2
+            exit 0
+          else
+            echo "Error exit code $PUBLISH_AS_IS" && exit $PUBLISH_AS_IS
+          fi
         env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Push Version Update
+        uses: ad-m/github-push-action@master
+        with:
+          branch: issue-93-gh-actions
+          github_token: ${{ secrets.GITHUB_TOKEN }}
